extends Node
## Mirrors config.py — tuning constants for the GDScript port.

const VERSION := "v1.0.0"
const DESIGN_WIDTH := 900
const DESIGN_HEIGHT := 720
const FPS := 60

const CLICK_IPS_FRACTION := 0.055
const CLICK_DEALER_BONUS := 0.10
const CLICK_CRIT_CHANCE := 0.05
const CLICK_CRIT_MIN := 2.0
const CLICK_CRIT_MAX := 8.0
const CLICK_HUSTLE_WINDOW := 2.0
const CLICK_HUSTLE_CLICKS := 8
const CLICK_HUSTLE_DURATION := 6.0
const CLICK_HUSTLE_MULT := 2.35

const FIRST_PRESTIGE_EARNINGS := 20_000_000.0
const FIRST_PRESTIGE_DEALERS := 20
const FIRST_PRESTIGE_RACKETS := 8
const FIRST_PRESTIGE_CHOPS := 4
const FIRST_PRESTIGE_RANK := "Made Man"
const PRESTIGE_EARNINGS_GROWTH := 8.0

const MANAGER_INCOME_MULT := 1.5
const AUTOSAVE_INTERVAL := 30.0
const OFFLINE_CAP_HOURS := 12.0
const OFFLINE_EFFICIENCY := 0.6
const SHOW_PARTICLES := true
